### ISSUE TITLE
Documentation for REST API

### ISSUE THREAD

**Issue by darkzbaron** [XjSv/Cooked#41] opened 2024-07-29 14:05 UTC
**Is your feature request related to a problem? Please describe.**
A documentation for the rest API

**Describe the solution you'd like**
The document of the rest API as mentionned in the readme

**Describe alternatives you've considered**

**Additional context**
Some examples api calls

**Comment by XjSv** [comment] 2024-07-29 17:19
@darkzbaron This was way before I started to maintain Cooked but it seems like the REST API was enabled for the cp_recipe custom post type:

```php
'show_in_rest' => true,
'rest_base' => 'cooked_recipe',
'rest_controller_class' => 'WP_REST_Posts_Controller',
```

Which means that you can use the WordPress REST API to get recipes. 

**For example**
https://www.example.com/wp-json/wp/v2/cooked_recipe

The same thing should be possible with the recipe categories but I see a bug that might make it not work. When fixed it should be accessable via: 

https://www.example.com/wp-json/wp/v2/recipe_category

I will expand the documentation to include this for the upcoming v1.8.1 release.

**Comment by XjSv** [comment] 2024-07-29 18:20
I have started to create the doc page here: https://github.com/XjSv/Cooked/wiki/REST-API
I will keep this issue open until the issue is fixed with recipe_category.

**Comment by darkzbaron** [comment] 2024-07-31 13:55
Thanks so much. I am interested to publish recipe. Do you think it's possible?

**Comment by XjSv** [comment] 2024-07-31 21:44
Yes it's certainly possible, I was able to test it just now.

What you can do is:

curl -X POST https://www.example.com/wp-json/wp/v2/cooked_recipe \
    -u "USERNAME:APPLICATION_PASSWORD" \
    -H "Content-Type: application/json" \
    -d '{
        "title": "My New Recipe",
        "content": "This is the content of the recipe.",
        "status": "publish"
    }'

For the password, check this documentation for how to create an Application Password: https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/#basic-authentication-with-application-passwords

**Comment by darkzbaron** [comment] 2024-08-01 10:02
Amazing, you saved my day! Thank you so much!

**Closed** 2024-08-04 21:59 UTC
Labels: enhancement
